#!/usr/bin/env bash

# ./rl result/file.txt
executable="$1"
set -e
set -x 
shift 1 || (echo "ERROR: $0 executable" && exit 1)

# set -x 
cd "$(dirname "$0")"/scripts
echo $PWD
source common.sh
cd $ROOT

build $executable
copy_program_over $executable
adb push stress_test.sh /data/local/tmp
run_program $executable "$@"

# ndk-build NDK_DEBUG=1
# adb push libs/armeabi-v7a/opencl_aes /data/local/tmp
# adb push jni/eng_opencl_aes.cl /data/local/tmp
# adb push stress_test.sh /data/local/tmp
# adb shell ./data/local/tmp/opencl_aes "$@"
